services:
  vae:
    image: saundersp/vae
    pull_policy: never
    build:
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./logs:/home/vae/logs
      - ./data:/home/vae/data:ro
      - ./jupyter:/home/vae/jupyter
      - ./__pycache__:/home/vae/__pycache__
      - ./.ipynb_checkpoints:/home/vae/.ipynb_checkpoints
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
